### ISSUE TITLE
建议分别为不同地区的中文变体选择符合相应地区标准的中文字体

### ISSUE THREAD

**Issue by Buernia** [starkshaw/wikipedia-stylesheets#1]
如题。

**Comment by starkshaw** [comment]
将在日后经过测试后加入。

另外我已经标注了 zh-CN.

**Comment by starkshaw** [comment]
@Buernia 针对 Neo-Grotesque 已经增补繁体中文（香港）以及繁体中文（台湾）。

**Comment by starkshaw** [comment]
针对 Classic 将会日后更新。

**Comment by starkshaw** [comment]
已经增补 Classic 样式的繁体中文（台湾）版本，并且加入对 macOS Sierra 的支持。

**Comment by starkshaw** [comment]
如果有更多问题，请重新打开。
